######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 25 14:47:04 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/sun.h
FORMS += src/sun.ui
SOURCES += src/main.cpp src/sun.cpp
