######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 25 14:47:21 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/simpleForm.h
SOURCES += src/main.cpp src/simpleForm.cpp
